services:
  postgres:
    image: postgres:15
    ports:
      - 10000:5432
    environment:
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    volumes:
      - $DATABASE_ROOT:/var/lib/postgresql/data

  spring:
    build: ./be
    ports:
      - 10100:80
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/$DATABASE_USERNAME
      - SPRING_DATASOURCE_USERNAME=$DATABASE_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$DATABASE_PASSWORD
      - STEAM_USERNAME=$STEAM_USERNAME
      - STEAM_PASSWORD=$STEAM_PASSWORD
    volumes:
      - $GAMES_ROOT:/root/Steam/steamapps
    depends_on:
      - postgres

  solidjs:
    build: ./fe
    ports:
      - 10200:80
    depends_on:
      - spring
